apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    func: ingress
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  # ingressClassName: nginx
  tls:
    - hosts:
      - "{{ .Chart.Name }}.{{ .Values.namespace }}.asiainnovationlab.sehlat.io"
      secretName: chatdoc-tls
  rules:
  - host: "{{ .Chart.Name }}.{{ .Values.namespace }}.asiainnovationlab.sehlat.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.port }}
